kind: ConfigMap
apiVersion: v1
metadata:
  name: webspa-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_URLS: http://0.0.0.0:80
  CallBackUrl: http://{{ .Values.hostName }}:8080
  DPConnectionString: basketdata
  BasketUrl: http://{{ .Values.hostName }}/gateway/
  IdentityUrl: http://{{ .Values.hostName }}/identity
  IdentityUrlHC: http://identity-api/hc
  OrchestratorType: K8S
  PATH_BASE: /
  PurchaseUrl: http://{{ .Values.hostName }}/gateway/
  PurchaseUrlHC: http://apigateway/hc
  SignalrHubUrl: http://{{ .Values.hostName }}/gateway/
  UseCustomizationData: "True"
  UseLoadTest: "False"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: webspa
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webspa
  template:
    metadata:
      labels:
        app: eshop
        service: webspa
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "webspa"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
    spec:
      containers:
        - name: webspa
          image: eshopdapr/webspa:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: webspa-http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: webspa-cm

---

kind: Service
apiVersion: v1
metadata:
  name: webspa
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
spec:
  ports:
    - port: 8080
      targetPort: webspa-http
      name: http
  type: LoadBalancer
  selector:
    service: webspa
