kind: ConfigMap
apiVersion: v1
metadata:
  name: webspa-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
data:
  ASPNETCORE_ENVIRONMENT: Docker
  ASPNETCORE_URLS: http://0.0.0.0:80
  CallBackUrl: http://{{ .Values.hostName }}/spa/
  DPConnectionString: basketdata
  BasketUrl: http://{{ .Values.hostName }}/gateway/
  IdentityUrl: http://{{ .Values.hostName }}/identity
  IdentityUrlHC: http://identity-api/hc
  OrchestratorType: K8S
  PATH_BASE: /
  PurchaseUrl: http://{{ .Values.hostName }}/gateway/
  PurchaseUrlHC: http://apigateway/hc
  SignalrHubUrl: http://{{ .Values.hostName }}/gateway/
  UseCustomizationData: "True"
  UseLoadTest: "False"

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: webspa
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webspa
  template:
    metadata:
      labels:
        app: eshop
        service: webspa
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "webspa"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
    spec:
      containers:
        - name: webspa
          image: eshopdapr/webspa:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: webspa-http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: webspa-cm

---

kind: Service
apiVersion: v1
metadata:
  name: webspa
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
spec:
  ports:
    - port: 80
      targetPort: webspa-http
      name: http
  selector:
    service: webspa

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webspa-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths: 
      - path: /spa(/.*)
        pathType: Prefix
        backend:
          service:
            name: webspa
            port: 
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webspa-ingress-redirect
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: webspa
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "http://{{ .Values.hostName }}/spa/"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths: 
      - path: /spa
        pathType: Exact
        backend:
          service:
            name: webspa
            port: 
              name: http
